# Conclusions

<!-- The primary indicator of stock status, CPUE, shows a positive signal for all LFAs. CPUE remains at very high levels at or near the highest value in the time series of for each LFA and remain well above the USR and LRP. Landings, though not yet complete remain high in all LFAs for their respective time series with effort staying relatively consistent. For the LFAs where bycatch was estimated, 2019 shows a decrease for all species recorded. -->

The primary indicators show strong positive signals for this stock. The stock status indicator, CPUE, has increased dramatically in the last ten years. The primary indicator for exploitation, the CCIR models from the recruitment trap data, indicates a reduction of exploitation in the inshore areas where this data is available. It should be noted that fishing effort has moved to more offshore areas that were not previously heavily exploited and are not monitored for exploitation. The recruitment trap data for the 2018–19 fishing season was not available for this report.
The conservation measures that have been put in place in other LFAs since the late 1990s and early 2000s, including increasing MLS, protecting window-sized Lobster, returning large females, and v-notching programs, have increased reproductive potential and productivity in respective LFAs. The impacts of some conservation measures can be detected in some of the biological indicator trends (Cook et al. 2020). These conservation measures should be encouraged, as protecting the reproductive components of the stock will buffer the impacts of years with suboptimal environmental conditions for Lobster production.
Precautionary approach reference points that were adopted following the 2018 Framework review are illustrated in Figure 6. The phase plot shows the relationship between commercial catch rates and CCIR exploitation rate in relation to the reference points USR, LRP, and RR. The trend shows increasing catch rates and decreasing exploitation in recent years. The CPUE index is well above the USR, suggesting the current status of LFA 33 is well within the healthy zone, and exploitation was below the RR for the 2017-18 fishing season.
The removal reference is to be adjusted depending on the stock’s abundance and its location in the three stock status zones. In the cautious zone, the adjustment of the RR does not have to follow a linear relationship, but a progressive reduction in removals is required.

```{r hcr, include=TRUE, echo=FALSE, warning=FALSE, message=FALSE, comment = FALSE, error = FALSE, fig.cap="Phase plot using the three-year running median of Catch Per Unit Effort and three-year running median of Continuous Change in Ratio exploitation index compared against the proposed Upper Stock Reference (USR) and Limit Reference Point (LRP) based on commercial catch rates. The Removal Reference (RR) is the 75th quantile break of the posterior distribution for the maximum exploitation index."}

# run this "bio/bio.lobster/inst/LFA2733Framework/Assessment/1.IndicatorEstimation.CohortAnalysis.r"
# and this "bio/bio.lobster/inst/LFA2733Framework/Assessment/ContextualIndicators.r"



# Phase plot for conclusions and advice

#x11(width=8,height=7)
 
x = read.csv(file.path(figdir,"CatchRateRefs33.csv"))
y = read.csv(file.path(figdir,"ExploitationRefs33.csv"))
		RR75 = 0.8146457
		usr = 0.2840067
		lrp = 0.1420034


hcrPlot(B=x$running.median[x$YEAR>2005],mF=y$running.median,USR=usr,LRP=lrp,RR=RR75,yrs=2006:2018,ylims=c(0,1),xlims=NULL,labels=c('USR','LRP','RR'),RRdec=F, ylab = 'Exploitation', xlab = 'CPUE',yr.ends=T) 
#hcrPlot(B=x$CPUE[x$YEAR>2005],mF=y$ERfm,USR=usr,LRP=lrp,RR=RR75,yrs=2006:2018,ylims=c(0,1),xlims=NULL,labels=c('USR','LRP','RR'),RRdec=F, ylab = 'Exploitation', xlab = 'CPUE',yr.ends=T) 
#savePlot(file.path(figdir,'PhasePlot33.png'),type='png')

```