---
title:  "Stock Status Update of Lobster (*Homarus americanus*) in Lobster Fishing Areas 36-38 for 2022"
french_title: "Insérez le titre ici ; le titre doit être exactement comme il apparaît sur la page de couverture, mais en majuscule (*Nom latin de l'espèce*)."
title_short: "Short title"
year: 2022
month: Month
french_month: Mois
report_number: 999 # This *must* be numeric! E.g., not `nnn`.
approver: |
  Approver Name\
  Regional Director
approval_year: 2022
approval_month: Month
approval_day: 01
work_done_year: 202
work_done_month: September
branch: Science Branch # French: Direction des sciences
region: Maritimes Region
french_region: Région du Maritimes
isbn: "ISBN-Here"
cat_no: "Cat-Number-Here"
output:
 csasdown::sr_word:
   french: false
   prepub: false
   # copy_sty is a toggle to copy the style file from the csasdown package every time you compile
   # the document. If false, any changes you have made to the style file in your project
   # will remain between compilations. If true, your changes will be lost when you compile
   copy_sty: true
   # line_nums is a toggle to show line numbers on the left side of the page. 
   line_nums: true
   # line_nums_mod represents showing every Nth line if line_nums is true
   line_nums_mod: 1
   # draft_watermark is a toggle to show/not show a DRAFT watermark across every page
   draft_watermark: false
   # highlight is the theme to use for code output. Must be one of the list given by:
   # pandoc --list-highlight-styles
   # which are:
   # pygments, tango, espresso, zenburn, kate, monochrome, breezedark, haddock
   # or the name of a custom *.latex file which is most easily made by copying one from 
   # the csasdown library 'themes' directory, this directory on your machine:
   # file.path(.libPaths(), "csasdown", "themes")
   # to your working directory (the one containing index.Rmd)
   # To change the foreground text color, change the RGB value in the line containing
   # 'DefineVerbatimEnvironment'
   # To change background color, change the RGB values in the line containing 'shadecolor'
   highlight: tango
type:
  sr
# ------------
# End of options to set
knit: (function(input, ...) {
       csasdown::render('_bookdown.yml')
      })
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
lot: true
lof: true
# Any extra LaTeX code for the header:
# header-includes:
# - \usepackage{tikz}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(dplyr)
library(readr)
library(tibble)
library(rosettafish)
library(csasdown)
```
```{r bilingual-code, cache=FALSE}
options(
  # Prevent xtable from adding a timestamp comment to the table code it produces
  xtable.comment = FALSE,
  # Do not allow kableExtra to load packages, we add them manually in csasdown
  kableExtra.latex.load_packages = FALSE,
  # Stop chunk output (echo) running into the margins
  width = 80,
  # Do not use scientific notation (stops tables from showing 1.2e3, etc.)
  scipen = 999)

meta <- rmarkdown::metadata
meta_out <- rmarkdown::metadata$output
csl <- "csl/csas.csl"
options(OutDec = ".")
if (is.null(getOption("french"))) {
  stop("`french` was not set up correctly in YAML header in index.Rmd. ",
       "It must be true or false",
       call. = FALSE)
}
if (getOption("french")) {
  csl <- "csl/csas-french.csl"
  options(OutDec = ",")
}
# This hook simplifies document translation for the author.
# When building in French, it draws a box around paragraphs contained in chunks
#  which have the option `needs_trans = TRUE`. It also labels
#  the box with a "Needs translation" tag in red and the chunk label in blue.
# You need to change the `needs_trans` option to `FALSE` for a chunk once you
#  have inserted the translated text into it. You will get a utf-8 error if
#  you leave it as `TRUE` and there is French in the chunk.
#  This function assumes you are translating from English to French.
#  If you wrote your document in French and want to translate to English,
#  put a ! before `getOption("french")` below and add the `need_trans`
#  chunk options to your English paragraph chunks instead of the French ones.
#  
#  IMPORTANT NOTES
#  - Use `csasdown::render_resdoc()` to render the document. This runs a
#    pre-processing step which ensures any inline R chunks
#    `r print("Like this one")` are taken care of correctly and that all
#    backslash variables (eg. \pi, \alpha, \@ref, \cite) are all processed
#    correctly.
#  - French latex places a space before the colon by default so if you need a colon
#    with no space before it, use \\hc .
knit_hooks$set(needs_trans = function(before, options){
  if(getOption("french") && options$needs_trans){
    if (before){
      paste0("\\
   \\begin{lrbox}{\\userinput}
   \\begin{minipage}{\\dimexpr\\linewidth-2\\fboxsep-2\\fboxrule}
   \\textcolor{red}{\\textbf{Needs translation - \\textcolor{blue}{knitr chunk: ", options$label, "}}}
   \\begin{lstlisting}
  ")
    } else {
      "
   \\end{lstlisting}
   \\end{minipage}
   \\end{lrbox}
   \\noindent
   \\fbox{\\usebox{\\userinput}}
  "
    }
  }
})
```
---
title: `r ifelse(fr(), meta$french_title, meta$title)`
month: `r ifelse(fr(), meta$french_month, meta$month)`
region: `r ifelse(fr(), meta$french_region, meta$region)`
csl: `r csl`
---
