# Context

The scientific basis for assessing the status of American Lobster stocks in Lobster Fishing
Areas (LFAs) 27–33 was examined at a framework meeting on January 23–24, 2018 (Cook et
al. 2020). This was followed by an assessment held on October 1, 2018, that provided advice
only for LFA 33 to align timing of science advice with data availability and the fisheries
management cycle (DFO 2019a).
The Framework review identified and agreed upon primary, secondary, and contextual
indicators to be used for the assessment of this stock. Some indicators are directly linked to
stock health and status (e.g., abundance), whereas others describe the population
characteristics (e.g., size structure) or ecosystem considerations (e.g., temperature). For the
purposes of a stock status update, only the primary and secondary indicators are reported.
This Science Response Report results from the Science Response Process of October xx, 2020,
on the Stock Status Update for American Lobster Fishing Areas 33.