# Background

A reference: [@francis2011].

## Description of the fishery

Commercial lobster fishing in LFAs 35 occurs in the Bay of Fundy (Figure 1) and borders the  biggest lobster fishery in the Canadian Northwest Atlantic: LFA 34, which has the highest landings of approximately 25,000 tonnes (t) (mean of last 5 years) and the most participants of any LFA in Canada. Landings in LFAs 35 began a long-term increase in the mid-1990s, and current landings are near record highs. This increase in landings occurred in most of the Gulf of Maine regions as well as for many other lobster stocks in Atlantic Canada.


The fishery is managed by input controls including a minimum legal size (MLS, 82.5 mm Carapace Length (CL)), prohibition on landing of both egg-bearing and V-notched (with no setal hairs) females, limited entry, fishing season ( October 14th - December 31st) and trap limits (300). Other management measures include the requirement of vents to allow sublegal sized lobster to escape and biodegradable trap mechanisms to mitigate ghost fishing by lost traps.