p = bio.lobster::load.environment()
require(devtools)
require(bio.lobster)
require(bio.utilities)
require(sf)
require(ggplot2)
require(dplyr)
require(bio.ccir)
require(rstan)

la()
p$yrs <- NULL #ensuring empty variable

#Data Prep
#----------------------------

assessment.year="2025" 
p$yr=p$current.assessment.year 
#logs = lobster.db('process.logs.redo') #(only run if need to update)
logs = lobster.db('process.logs')

lobster.db('ccir.redo')
ccir_data = subset(ccir_data,YEAR<=assessment.year) #subsets data to proper years

inp = read.csv(file.path(bio.directory,'bio.lobster.data','misc','ccir','ccir_inputs.csv'))
load(file.path(bio.directory,'bio.lobster.data','misc','ccir','ccir_groupings.rdata')) #object names Groupings
load(file.path(bio.directory,'bio.lobster.data','misc','ccir','ccir_seasons.rdata'))

# ============================================================
# COMPILE CCIR DATA - LFA 33
# ============================================================

dat <- ccir_compile_data(
  x = ccir_data,
  log.data = logs,
  area.defns = Groupings[7],
  size.defns = inp,
  season.defns = Seasons,
  sexs = 1.5
)

# sexs = 1.5 means no sex definition


# ============================================================
# DIRECTORY STRUCTURE
# ============================================================

save_dir <- file.path(project.datadirectory("bio.lobster", "assessments",
                                            "33.34.41.framework", "ccir.model.testing"))

# Main model directories
binomial_dir <- file.path(save_dir, "summary", "binomial")
binomial_temp_dir <- file.path(save_dir, "summary", "binomial.temp")

# LFA 33 directories
binomial_lfa33_dir <- file.path(binomial_dir, "lfa33")
binomial_temp_lfa33_dir <- file.path(binomial_temp_dir, "lfa33")

# Full Stan model fits
binomial_fit_dir <- file.path(binomial_lfa33_dir, "fits")
binomial_temp_fit_dir <- file.path(binomial_temp_lfa33_dir, "fits")

# Individual model summaries
binomial_summary_dir <- file.path(binomial_lfa33_dir, "summaries")
binomial_temp_summary_dir <- file.path(binomial_temp_lfa33_dir, "summaries")

# Create all directories
dir.create(binomial_fit_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(binomial_summary_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(binomial_temp_fit_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(binomial_temp_summary_dir, recursive = TRUE, showWarnings = FALSE)

# Existing CCIR functions save full Stan model files here.
# We leave those functions unchanged and copy the files afterward.
package_ccir_dir <- file.path(project.datadirectory("bio.lobster"), "outputs", "ccir")


# ============================================================
# BINOMIAL MODEL
# ============================================================

out.binomial <- list()
attr(out.binomial, "model") <- "binomial"

for(i in 1:length(dat)) {
  
  print(paste("Running BINOMIAL model", i, "of", length(dat)))
  
  ds <- dat[[i]]
  
  # Run the existing CCIR binomial model
  x <- ccir_stan_run_binomial(dat = ds, save = TRUE)
  
  # Show the filename generated by the existing function
  print(paste("Model file generated:", x$file))
  
  # Identify the full model file saved by the package function
  full_model_file <- paste(x$file, "rdata", sep = ".")
  source_file <- file.path(package_ccir_dir, full_model_file)
  destination_file <- file.path(binomial_fit_dir, full_model_file)
  
  # Copy the full Stan model into our controlled LFA 33 directory
  if(file.exists(source_file)) {
    
    copied <- file.copy(source_file, destination_file, overwrite = TRUE)
    
    if(copied) {
      print(paste("Full model copied to:", destination_file))
    } else {
      warning(paste("Could not copy model file:", source_file))
    }
    
  } else {
    warning(paste("Full model file not found:", source_file))
  }
  
  # Create and save the individual model summary
  out.binomial[[i]] <- ccir_stan_summarize(x, fdir = binomial_summary_dir)
}


# ============================================================
# REBUILD BINOMIAL SUMMARY LIST
# ============================================================
# This allows the analysis to be restarted after a broken run.
# Existing summary files can be loaded without rerunning models.

d <- sort(list.files(binomial_summary_dir, full.names = TRUE))
d <- d[!file.info(d)$isdir]

print(paste("Number of binomial summary files found:", length(d)))

if(length(d) == 0) {
  stop("No binomial summary files found in: ", binomial_summary_dir)
}

out.binomial <- list()

for(i in 1:length(d)) {
  print(paste("Loading binomial summary:", basename(d[i])))
  load(d[i])
  out.binomial[[i]] <- out
}

# LFA 33 is represented by two areas
if(length(out.binomial) < 2) {
  stop("Expected at least two binomial summary files for LFA 33.")
}

out.binomial[[1]]$LFA <- "33W"
out.binomial[[2]]$LFA <- "33E"


# ============================================================
# BINOMIAL + TEMPERATURE MODEL
# ============================================================


for(i in 1:length(dat)) {
  
  print(paste(
    "Running BINOMIAL + TEMPERATURE model",
    i,
    "of",
    length(dat)
  ))
  
  ds <- dat[[i]]
  
  
  # ----------------------------------------------------------
  # Remove observations with missing temperature
  # ----------------------------------------------------------
  #
  # Temperature must be present for every observation passed
  # to Stan. Remove the corresponding observation from ALL
  # model vectors so that they remain synchronized.
  # ----------------------------------------------------------
  
  keep <- !is.na(ds$Temp)
  
  if(any(!keep)) {
    
    removed_dates <- ds$dates[!keep]
    
    print(paste(
      "Removing",
      sum(!keep),
      "observation(s) with missing temperature."
    ))
    
    print(paste(
      "Removed date(s):",
      paste(removed_dates, collapse=", ")
    ))
    
    ds$n <- sum(keep)
    ds$p <- ds$p[keep]
    ds$N <- ds$N[keep]
    ds$E <- ds$E[keep]
    ds$Cuml <- ds$Cuml[keep]
    ds$dates <- ds$dates[keep]
    ds$Temp <- ds$Temp[keep]
  }
  
  
  # ----------------------------------------------------------
  # Final consistency check
  # ----------------------------------------------------------
  
  stopifnot(
    length(ds$p) == ds$n,
    length(ds$N) == ds$n,
    length(ds$E) == ds$n,
    length(ds$Cuml) == ds$n,
    length(ds$dates) == ds$n,
    length(ds$Temp) == ds$n,
    !anyNA(ds$Temp)
  )
  
  
  # ----------------------------------------------------------
  # Run temperature model
  # ----------------------------------------------------------
  #
  # ccir_stan_run_binomial_temperature.r has been modified to:
  #
  #   iter   = 3500
  #   warmup = 1000
  #   thin   = 10
  #
  # This gives 250 saved post-warmup draws per chain.
  # ----------------------------------------------------------
  
  x <- ccir_stan_run_binomial_temperature(
    dat=ds,
    save=TRUE
  )
  
  
  # ----------------------------------------------------------
  # Copy FULL Stan model into controlled directory
  # ----------------------------------------------------------
  
  full_model_file <- paste(
    x$file,
    "rdata",
    sep="."
  )
  
  source_file <- file.path(
    package_ccir_dir,
    full_model_file
  )
  
  destination_file <- file.path(
    binomial_temp_fit_dir,
    full_model_file
  )
  
  if(file.exists(source_file)) {
    
    file.copy(
      from=source_file,
      to=destination_file,
      overwrite=TRUE
    )
    
    print(paste(
      "Full temperature model copied to:",
      destination_file
    ))
    
  } else {
    
    warning(paste(
      "Full temperature model file not found:",
      source_file
    ))
  }
  
  
  # ----------------------------------------------------------
  # Create and save model summary
  # ----------------------------------------------------------
  
  out.binomial.temp[[i]] <- ccir_stan_summarize(
    x,
    fdir=binomial_temp_summary_dir
  )
}


# ============================================================
# COMPILE BINOMIAL + TEMPERATURE SUMMARIES
# ============================================================


d.temp <- list.files(
  binomial_temp_summary_dir,
  full.names=TRUE
)

d.temp <- d.temp[
  !file.info(d.temp)$isdir
]


out.binomial.temp <- list()


for(i in 1:length(d.temp)) {
  
  load(d.temp[i])
  
  out.binomial.temp[[i]] <- out
}


# ------------------------------------------------------------
# Assign LFA labels
# ------------------------------------------------------------

out.binomial.temp[[1]]$LFA <- "33W"
out.binomial.temp[[2]]$LFA <- "33E"


# ------------------------------------------------------------
# Collapse summaries
# ------------------------------------------------------------

ouBin.temp <- ccir_collapse_summary(
  out.binomial.temp
)

attr(
  ouBin.temp,
  "model"
) <- "binomial.temp"


# ------------------------------------------------------------
# Save compiled temperature model
# ------------------------------------------------------------

binomial_temp_compiled_file <- file.path(
  binomial_temp_dir,
  "compiledBinomialTempModels33.rdata"
)


save(
  ouBin.temp,
  file=binomial_temp_compiled_file
)


print(paste(
  "Compiled BINOMIAL + TEMPERATURE model saved to:",
  binomial_temp_compiled_file
))


# ============================================================
# FINAL DIRECTORY CHECK
# ============================================================

print("============================================================")
print("BOTH MODEL SETS COMPLETE")
print("============================================================")

print(paste("Binomial fits:        ", binomial_fit_dir))
print(paste("Binomial summaries:   ", binomial_summary_dir))
print(paste("Binomial compiled:    ", binomial_compiled_file))
print(paste("Temperature fits:     ", binomial_temp_fit_dir))
print(paste("Temperature summaries:", binomial_temp_summary_dir))
print(paste("Temperature compiled: ", binomial_temp_compiled_file))

# ============================================================
# CALCULATE WAIC FROM SAVED CCIR STAN FITS
#
# Purpose:
#   Calculate WAIC from previously saved BINOMIAL and
#   BINOMIAL + TEMPERATURE Stan fits.
#
# Important:
#   This script does NOT rerun the Stan models.
#   It reconstructs the pointwise binomial log-likelihood
#   from the posterior draws of phat and the observed E and N.
#
# Model likelihood:
#   E[i] ~ Binomial(N[i], phat[i])
#
# where:
#   E    = observed number of successful/reference lobsters
#   N    = total number of lobsters/traps
#   phat = posterior predicted probability
# ============================================================


# ------------------------------------------------------------
# 1. Directories
# ------------------------------------------------------------

# These objects should already point to the directories
# containing the saved model fits.

# Example:
#
# binomial_fit_dir <- file.path(
#     ccir.model.testing,
#     "summary/binomial/fits"
# )
#
# binomial_temp_fit_dir <- file.path(
#     ccir.model.testing,
#     "summary/binomial.temp/lfa33/fits"
# )


# ------------------------------------------------------------
# 2. Function to calculate WAIC
# ------------------------------------------------------------

get_waic <- function(fit_file) {
  
  # Load saved fit
  load(fit_file)
  
  # ----------------------------------------------------------
  # Extract posterior draws of phat
  # ----------------------------------------------------------
  
  phat_draws <- rstan::extract(
    out$fit,
    pars = "phat"
  )$phat
  
  # Ensure a simple matrix
  # Rows = posterior draws
  # Columns = observations
  phat_draws <- as.matrix(phat_draws)
  
  
  # ----------------------------------------------------------
  # Observed data
  # ----------------------------------------------------------
  
  E <- out$dat$E
  N <- out$dat$N
  
  
  # ----------------------------------------------------------
  # Pointwise log-likelihood
  #
  # Each posterior draw gets a likelihood for each
  # observation.
  #
  # Result:
  #   rows    = posterior draws
  #   columns = observations
  # ----------------------------------------------------------
  
  log_lik <- t(sapply(
    1:nrow(phat_draws),
    function(i) {
      
      dbinom(
        E,
        size = N,
        prob = phat_draws[i, ],
        log = TRUE
      )
      
    }
  ))
  
  
  # ----------------------------------------------------------
  # Log pointwise predictive density (lppd)
  # ----------------------------------------------------------
  
  lppd <- sum(
    log(
      apply(
        log_lik,
        2,
        function(x) {
          mean(exp(x))
        }
      )
    )
  )
  
  
  # ----------------------------------------------------------
  # Effective number of parameters
  # ----------------------------------------------------------
  
  p_waic <- sum(
    apply(
      log_lik,
      2,
      var
    )
  )
  
  
  # ----------------------------------------------------------
  # WAIC
  # ----------------------------------------------------------
  
  waic <- -2 * (lppd - p_waic)
  
  
  # ----------------------------------------------------------
  # Return results
  # ----------------------------------------------------------
  
  data.frame(
    file = basename(fit_file),
    WAIC = waic,
    p_WAIC = p_waic,
    lppd = lppd
  )
}


# ------------------------------------------------------------
# 3. Test on one BINOMIAL + TEMPERATURE model
# ------------------------------------------------------------

f.temp <- list.files(
  binomial_temp_fit_dir,
  full.names = TRUE,
  pattern = "\\.rdata$"
)[1]

test_waic <- get_waic(f.temp)

test_waic


# ------------------------------------------------------------
# Expected result for the first LFA 33 temperature model
# ------------------------------------------------------------
#
# Approximately:
#
#       WAIC    = 345.632
#       p_WAIC  =   3.757
#       lppd    = -169.059
#
# Small differences in the final decimals are possible.
#
# If these values are reproduced, the WAIC calculation has
# been verified against the manually calculated result.
# ------------------------------------------------------------

# ============================================================
# WAIC COMPARISON: BINOMIAL vs BINOMIAL + TEMPERATURE
# ============================================================

# ------------------------------------------------------------
# Function to calculate WAIC from a saved Stan fit
# ------------------------------------------------------------

get_waic <- function(f) {
  
  load(f)
  
  # Extract posterior draws of phat
  phat_draws <- rstan::extract(
    out$fit,
    pars = "phat"
  )$phat
  
  # Calculate pointwise log-likelihood
  log_lik <- sapply(
    1:nrow(phat_draws),
    function(i) {
      dbinom(
        out$dat$E,
        size = out$dat$N,
        prob = phat_draws[i, ],
        log = TRUE
      )
    }
  )
  
  # lppd
  lppd <- sum(
    log(
      apply(log_lik, 2, function(x) {
        mean(exp(x))
      })
    )
  )
  
  # Effective number of parameters
  p_waic <- sum(
    apply(log_lik, 2, var)
  )
  
  # WAIC
  waic <- -2 * (lppd - p_waic)
  
  # Return results
  data.frame(
    file = basename(f),
    WAIC = waic,
    p_WAIC = p_waic,
    lppd = lppd
  )
}


# ============================================================
# BINOMIAL MODELS
# ============================================================

bin.files <- list.files(
  binomial_fit_dir,
  full.names = TRUE,
  pattern = "\\.rdata$"
)

length(bin.files)

bin.ic <- do.call(
  rbind,
  lapply(bin.files, get_waic)
)

bin.ic


# ============================================================
# BINOMIAL + TEMPERATURE MODELS
# ============================================================

temp.files <- list.files(
  binomial_temp_fit_dir,
  full.names = TRUE,
  pattern = "\\.rdata$"
)

length(temp.files)

temp.ic <- do.call(
  rbind,
  lapply(temp.files, get_waic)
)

temp.ic


# ============================================================
# MATCH BINOMIAL AND BINOMIAL + TEMPERATURE MODELS
# ============================================================

# Create filename used for matching
bin.ic$filename <- basename(bin.ic$file)
temp.ic$filename <- basename(temp.ic$file)

# Match corresponding models by filename
ic.compare <- merge(
  bin.ic,
  temp.ic,
  by = "filename",
  suffixes = c("_bin", "_temp")
)

# Calculate change in WAIC from adding temperature
#
# Negative Delta_WAIC = temperature improves model
# Positive Delta_WAIC = temperature worsens model
#
ic.compare$Delta_WAIC <-
  ic.compare$WAIC_temp - ic.compare$WAIC_bin

# Sort by filename
ic.compare <- ic.compare[
  order(ic.compare$filename),
]

# View comparison
ic.compare


# ============================================================
# OPTIONAL: SAVE THE WAIC COMPARISON
# ============================================================

write.csv(
  ic.compare,
  file = "binomial_vs_temperature_WAIC_comparison.csv",
  row.names = FALSE
)

##Potential Rewrites of major CCIR functions:
  
#' @export
ccir_stan_models_binomial_temperature_logistic <- function() {
  
  bino = '
  
  data {
    int<lower=1> n;                   // sample size
    vector<lower=0,upper=1>[n] p;     // observed proportion
    vector<lower=0,upper=1>[n] Cuml;  // cumulative landings
    int N[n];                         // total number observed
    int E[n];                         // number exploitable/legal
    real Temp[n];                     // temperature
    
    // Prior means and standard deviations
    real Ap;
    real Bp;
    real App;
    real Bpp;
    real Dp;
    real Dpp;
  }

  parameters {
    real A;                           // intercept
    real B;                           // cumulative landings coefficient
    real D;                           // temperature coefficient
  }

  transformed parameters {
    vector[n] pp;
    
    for (i in 1:n) {
      // Logistic formulation:
      // logit(pp) = A + B*Cuml + D*Temp
      pp[i] = inv_logit(A + B * Cuml[i] + D * Temp[i]);
    }
  }

  model {
    // Priors
    A ~ normal(Ap, App);
    B ~ normal(Bp, Bpp);
    D ~ normal(Dp, Dpp);

    // Binomial likelihood
    E ~ binomial(N, pp);
  }

  generated quantities {
    vector[n] phat;
    vector[n] ERp;
    
    for (i in 1:n) {
      phat[i] = pp[i];
      
      // Exploitation rate relative to the first observation,
      // calculated from the odds of exploitable lobster.
      ERp[i] = 1 -
        (phat[i] / (1 - phat[i])) /
        (phat[1] / (1 - phat[1]));
    }
  }
  
  '
  
  return(bino)
}


#' @export
ccir_stan_run_binomial_temperature_logistic <- function(
    dat,
    inits = c(A0 = 0.5, B0 = 0.5, D = 0.1),
    save = TRUE,
    season = NULL,
    test = NA
) {
  
  # ------------------------------------------------------------
  # Define prior means using the existing CCIR initialization
  # procedure.
  #
  # These are prior means, NOT Stan starting values.
  # ------------------------------------------------------------
  
  ins <- ccir_inits(
    dat,
    A0 = inits[1],
    B0 = inits[2]
  )
  
  dat$Ap <- as.numeric(ins[1])
  dat$Bp <- as.numeric(ins[2])
  
  # Prior standard deviations
  dat$App <- 5
  dat$Bpp <- 5
  
  # Temperature prior
  dat$Dp <- as.numeric(inits[3])
  dat$Dpp <- 0.4
  
  # Retained for compatibility with the existing data structure
  dat$phip <- 0
  dat$phipp <- 100
  
  
  # ------------------------------------------------------------
  # Model
  # ------------------------------------------------------------
  
  ccir_stan <- ccir_stan_models_binomial_temperature_logistic()
  
  
  # ------------------------------------------------------------
  # Parameters to monitor
  # ------------------------------------------------------------
  
  pars.to.monitor <- c(
    "A",
    "B",
    "D",
    "pp",
    "phat",
    "ERp"
  )
  
  
  # ------------------------------------------------------------
  # Run Stan
  # ------------------------------------------------------------
  
  fit <- stan(
    model_code = ccir_stan,
    model_name = "bino_logistic",
    fit = test,
    data = dat,
    iter = 3500,
    warmup = 1000,
    thin = 10,
    cores = 4,
    verbose = FALSE
  )
  
  
  # ------------------------------------------------------------
  # Output directory
  # ------------------------------------------------------------
  
  fdir <- file.path(
    project.datadirectory("bio.lobster"),
    "outputs",
    "ccir"
  )
  
  if (!dir.exists(fdir)) {
    dir.create(
      fdir,
      recursive = TRUE,
      showWarnings = FALSE
    )
  }
  
  
  # ------------------------------------------------------------
  # Construct output filename
  #
  # "Logistic" is explicitly included so that this cannot
  # overwrite the original CCIR output.
  # ------------------------------------------------------------
  
  ti <- 1
  
  if (!is.null(season)) {
    ti <- season
  }
  
  fname <- paste(
    "LFA",
    dat$LFA,
    "Year",
    dat$Yr,
    ti,
    "Grid",
    paste(min(dat$Grid), max(dat$Grid), sep = "-"),
    "Season",
    paste(min(dat$Seas), max(dat$Seas), sep = "-"),
    "Sex",
    dat$Sex,
    dat$method,
    "Logistic",
    sep = "."
  )
  
  
  # ------------------------------------------------------------
  # Output object
  # ------------------------------------------------------------
  
  out <- list(
    fit = fit,
    dat = dat,
    file = fname,
    test = test
  )
  
  
  # ------------------------------------------------------------
  # Save
  # ------------------------------------------------------------
  
  if (save) {
    save(
      out,
      file = file.path(
        fdir,
        paste(fname, "rdata", sep = ".")
      )
    )
  }
  
  
  return(out)
}

  