# Sources of information

Claytor, R. and Allard, J. 2003. Change-in-ratio Estimates of Lobster Exploitation Rate Using Sampling Concurrent with Fishing. Can. J. Fish. Aquatic Sci. 60(10): 1190-1203.

Cook, A.M., Hubley, P.B., Denton, C., and Howse, V. 2018. 2018 Framework Assessment of American Lobster (Homarus americanus) in LFA 27-33. DFO Can. Sci. Advis. Sec. Res. Doc. 2018/nnn. 

DFO. 2009. A fishery decision-making framework incorporating the Precautionary Approach.

DFO. 2020.  Assessment of Lobster (Homarus Americanus) in Lobster Fishing Areas 27-32. DFO Can. Sci. Advis. Sec. Sci. Advis. Rep. 2020/nnn. 

Gendron, L., and Savard, G. 2012. Lobster Stock Status in the Coastal Waters of Quebec (LFAs 15 to 22) in 2011 and Determination of Reference Points for the Implementation of a Precautionary Approach in the Magdalen Islands (LFA 22). DFO Can. Sci. Advis. Sec. Res. Doc. 2012/010. 

Tremblay, M.J., Pezzak, D.S., and Gaudette, J. 2012. Development of Reference Points for Inshore Lobster in the Maritimes Region (LFAs 27-38). DFO Can. Sci. Advis. Sec. Res. Doc. 2012/028.

Tremblay, M.J., Pezzack, D.S., Gaudette, J., Denton, C., Cassista-Da Ros, M., and Allard, J. 2013. Assessment of Lobster (Homurus americanus) off Southwest Nova Scotia and in the Bay of Fundy (Lobster Fishing Areas 34-38). DFO Can. Sci. Advis. Sec. Res. Doc. 2013/78. 
